import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
<<<<<<< HEAD
import { Navbar } from "@/components/ui/navbar";
import { MobileBottomNav } from "@/components/revolt/mobile-bottom-nav";
=======

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
>>>>>>> 1814efffe67565d8d776da80e5f508d1e4752b08

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
<<<<<<< HEAD
    return (
        <html lang="es" suppressHydrationWarning>
            <body className="antialiased font-sans" suppressHydrationWarning>
                <ThemeProvider
                    attribute="class"
                    defaultTheme="dark"
                    enableSystem={false}
                    disableTransitionOnChange
                >
                    <Navbar />
                    <main className="pb-20 md:pb-0">{children}</main>
                    <Footer />
                    <MobileBottomNav />
                    <WhatsAppButton />
                </ThemeProvider>
            </body>
        </html>
    );
=======
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
>>>>>>> 1814efffe67565d8d776da80e5f508d1e4752b08
}
